/*

Create an SQL script that just contains a “SELECT * FROM …” command for each table in
your database. Name this file “ViewTables.sql”

*/

SELECT * FROM PIZZA;
SELECT * FROM ORDERS;
SELECT * FROM DINE_IN;
SELECT * FROM DELIVERY;
SELECT * FROM PICKUP;
SELECT * FROM TOPPINGS;
SELECT * FROM TOPPINGLIST;
SELECT * FROM DISCOUNTS;
SELECT * FROM ORDERDISCOUNT;
SELECT * FROM PIZZADISCOUNT;
SELECT * FROM BASEPRICE;
SELECT * FROM CUSTOMER;